language: node_js
node_js:
  - 10
cache:
  directories:
  - node_modules
before_install:
  - yarn global add firebase-tools ionic
after_success:
  - ionic build --prod --service-worker
  - firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN
branches:
  only:
    - master