language: node_js
node_js:
  - 10
cache:
  directories:
  - node_modules
before_install:
  - npm i -g firebase-tools ionic
script:
  - echo "skipping tests"
after_success:
  - ionic build --prod --service-worker
  - firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN
branches:
  only:
    - master
